name: Sample

on:
  push:
    branches:
      - '**'

jobs:
  primary_routine:
    name: Primary routine
    runs-on: ubuntu-latest
    steps:
      - run: |
             echo "Running primary routine..."
             sleep 30
             echo "Done"
  
  dependency_scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Meterian Scan
        uses: MeterianHQ/meterian-github-action@v1.0.13
        env:
          METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
