name: Sample workflow

on: push

jobs:
  primary_routine:
    name: Primary routine
    runs-on: ubuntu-latest
    steps:
      - run: |
             echo "Running primary routine..."
             sleep 30
             echo "Done"
  
  meterian_scan:
    name: Meterian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Meterian scan
        uses: MeterianHQ/meterian-github-action@v1.0.13
        env:
          METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
